package model;
// Generated 9 juin 2022 04:45:24 by Hibernate Tools 4.3.1


import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * Assignment generated by hbm2java
 */
@Entity(name="Assignment")
public class Assignment  implements java.io.Serializable {


     @Id
     private int idassignment;
     private String name;
     private Integer startdate;
     private Integer duedate;
     private Boolean submitted;
     private String link;
     private String submission_path;
     private String filename;
    @ManyToMany(mappedBy = "assignments")
     private Set<Course> courses = new HashSet<>(0);

    public Assignment() {
        this.submitted = false;
    }

    public Assignment(int idassignment) {
        this.idassignment = idassignment;
        this.submitted = false;
    }
    public Assignment(int idassignment, String name, Integer startdate, Integer duedate, Set courses) {
       this.idassignment = idassignment;
       this.name = name;
       this.startdate = startdate;
       this.duedate = duedate;
       this.courses = courses;
       this.submitted = false;
    }

    public Assignment(int idassignment, String name, Integer startdate, Integer duedate, Boolean submitted, String link, String submission_path, String filename) {
        this.idassignment = idassignment;
        this.name = name;
        this.startdate = startdate;
        this.duedate = duedate;
        this.submitted = submitted;
        this.link = link;
        this.submission_path = submission_path;
        this.filename = filename;
    }    
    
   
    public int getIdassignment() {
        return this.idassignment;
    }
    
    public void setIdassignment(int idassignment) {
        this.idassignment = idassignment;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }
    public Integer getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Integer duedate) {
        this.duedate = duedate;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }

    public Boolean getSubmitted() {
        return submitted;
    }

    public void setSubmitted(Boolean submitted) {
        this.submitted = submitted;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getSubmission_path() {
        return submission_path;
    }

    public void setSubmission_path(String submission_path) {
        this.submission_path = submission_path;
    }
    
    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Override
    public String toString(){
        Long tmp = new Long(this.duedate) * 1000;
        Date date = new Date(tmp);
        Long tmp1 = new Long(this.startdate) * 1000;
        Date date1 = new Date(tmp1);
        DateFormat df = new SimpleDateFormat("dd MMM yyyy hh:mm:ss zzz");
        return "AssignmentId :"+Integer.toString(this.idassignment)+"\nName :"+this.name+"\nOpened Date :"+df.format(date)+"\nDue Date:"+df.format(date1);
    }
    
}


