package model;
// Generated 9 juin 2022 04:45:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Assignment generated by hbm2java
 */
public class Assignment  implements java.io.Serializable {


     private int idassignment;
     private String name;
     private Integer startdate;
     private Integer duedate;
     private Set courses = new HashSet(0);

    public Assignment() {
    }

	
    public Assignment(int idassignment) {
        this.idassignment = idassignment;
    }
    public Assignment(int idassignment, String name, Integer startdate, Integer duedate, Set courses) {
       this.idassignment = idassignment;
       this.name = name;
       this.startdate = startdate;
       this.duedate = duedate;
       this.courses = courses;
    }
   
    public int getIdassignment() {
        return this.idassignment;
    }
    
    public void setIdassignment(int idassignment) {
        this.idassignment = idassignment;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }
    public Integer getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Integer duedate) {
        this.duedate = duedate;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


