package model;
// Generated 9 juin 2022 04:45:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="User")
public class User  implements java.io.Serializable {


    @Id
    private int userid;
    private String username;
    private String fullname;
    private String password;
     @ManyToMany(cascade = { CascadeType.ALL })
     @JoinTable(
        name = "User_Course", 
        joinColumns = { @JoinColumn(name = "userid") }, 
        inverseJoinColumns = { @JoinColumn(name = "idcourse") }
     )
     private Set<Course> courses = new HashSet(0);

    public User() {
    }

	
    public User(int userid, String username, String password) {
        this.userid = userid;
        this.username = username;
        this.password = password;
    }
    public User(int userid, String username, String fullname, String password, Set courses) {
       this.userid = userid;
       this.username = username;
       this.fullname = fullname;
       this.password = password;
       this.courses = courses;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    
    @Override
    public String toString(){
        return "UserId :"+Integer.toString(this.userid)+"\nUsername :"+this.username+"\nFullname :"+this.fullname;
    }

}


